name: ci

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-20.04
    container: clojure:openjdk-19-tools-deps-1.11.1.1113-bullseye
    services:
      redis:
        image: redis:7.0
        # Health checks will wait until redis has started.
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      rabbitmq:
        image: heidiks/rabbitmq-delayed-message-exchange:3.9.13-management
        env:
          RABBITMQ_DEFAULT_USER: goose
          RABBITMQ_DEFAULT_PASS: top-gun
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: clj -X:test
        env:
          GOOSE_TEST_REDIS_HOST: redis
          GOOSE_TEST_REDIS_PORT: 6379
          GOOSE_TEST_RABBITMQ_HOST: rabbitmq
          GOOSE_TEST_RABBITMQ_PORT: 5672
          GOOSE_TEST_RABBITMQ_USERNAME: goose
          GOOSE_TEST_RABBITMQ_PASSWORD: top-gun
  lint:
    runs-on: ubuntu-20.04
    container: cljkondo/clj-kondo:2022.10.05-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Lint src
        run: clj-kondo --lint src/
      - name: Lint test
        run: clj-kondo --lint test/
      - name: Lint perf
        run: clj-kondo --lint perf/
